import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const pkgRoot = path.join(__dirname, '..');
const srcDir = path.join(pkgRoot, 'src');
const genDir = path.join(srcDir, 'generated');
const sourcePath = path.join(srcDir, 'tokens.style-dictionary.json');

/** @param {unknown} value */
function isTokenLeaf(value) {
  return (
    value !== null &&
    typeof value === 'object' &&
    !Array.isArray(value) &&
    'value' in value &&
    typeof /** @type {{ value?: unknown }} */ (value).value === 'string'
  );
}

/** @param {unknown} node */
function toRuntimeTokens(node) {
  if (isTokenLeaf(node)) {
    return /** @type {{ value: string }} */ (node).value;
  }

  if (node === null || typeof node !== 'object' || Array.isArray(node)) {
    throw new TypeError('Invalid token tree node');
  }

  /** @type {Record<string, unknown>} */
  const out = {};
  for (const [key, val] of Object.entries(node)) {
    out[key] = toRuntimeTokens(val);
  }
  return out;
}

const rawTree = JSON.parse(fs.readFileSync(sourcePath, 'utf8'));
const runtimeTree = toRuntimeTokens(rawTree);
const json = JSON.stringify(runtimeTree, null, 2);

const file = `/* eslint-disable */\n/* Generated by scripts/prebuild.mjs — do not edit manually */\nexport const tokens = ${json} as const;\nexport type NexuiTokens = typeof tokens;\n`;

fs.mkdirSync(genDir, { recursive: true });
fs.writeFileSync(path.join(genDir, 'tokens.ts'), file, 'utf8');
